// DESCRIPTION: Dashboard landing page for the Content Forge admin menu.
// DESCRIPTION: Shows what has been generated, Autopilot health, and where to go next.

import { __, sprintf } from '@wordpress/i18n';
import { useEffect, useState } from '@wordpress/element';
import apiFetch from '@wordpress/api-fetch';
import '../css/common.css';
import Header from './components/Header';
import Card from './components/Card';
import Button from './components/Button';
import Badge from './components/Badge';
import Notice from './components/Notice';
import StatTile from './components/StatTile';
import PromoPlugins from './components/PromoPlugins';

const pages = window.cforge?.pages || {};

// One tile per generator page, so every number routes back to the screen that made it.
const TILES = [
    { key: 'posts', label: __('Posts & pages', 'content-forge'), icon: '📄', href: pages.pagesPosts },
    { key: 'cpt', label: __('Custom post types', 'content-forge'), icon: '🗂️', href: pages.cpt },
    { key: 'users', label: __('Users', 'content-forge'), icon: '👤', href: pages.users },
    { key: 'comments', label: __('Comments', 'content-forge'), icon: '💬', href: pages.comments },
    { key: 'terms', label: __('Terms', 'content-forge'), icon: '🏷️', href: pages.taxonomies },
];

// Every generator already exposes DELETE /{base}/bulk as its delete-all.
const BULK_DELETE_PATHS = ['posts/bulk', 'comments/bulk', 'users/bulk', 'taxonomy/bulk'];

function DashboardApp() {
    const [data, setData] = useState(null);
    const [error, setError] = useState('');
    const [deleting, setDeleting] = useState(false);

    const load = async () => {
        try {
            const result = await apiFetch({ path: 'dashboard', method: 'GET' });
            setData(result);
        } catch (e) {
            setError(e.message || __('Could not load dashboard data.', 'content-forge'));
        }
    };

    useEffect(() => {
        load();
    }, []);

    const deleteAll = async () => {
        // eslint-disable-next-line no-alert
        if (!window.confirm(__('Delete all content generated by Content Forge? This cannot be undone.', 'content-forge'))) {
            return;
        }

        setDeleting(true);
        setError('');

        try {
            // Sequential, not parallel: four concurrent bulk deletes on a large
            // dataset is a reliable way to exhaust PHP workers.
            for (const path of BULK_DELETE_PATHS) {
                await apiFetch({ path, method: 'DELETE' });
            }
            await load();
        } catch (e) {
            setError(e.message || __('Some content could not be deleted.', 'content-forge'));
            await load();
        } finally {
            setDeleting(false);
        }
    };

    const counts = data?.counts || {};
    const total = data?.total || 0;
    const autopilot = data?.autopilot || {};
    const isEmpty = data && total === 0;

    return (
        <>
            <Header
                heading={__('Dashboard', 'content-forge')}
                subheading={
                    isEmpty
                        ? __("Let's generate your first batch of content.", 'content-forge')
                        : __("Everything you've generated, at a glance.", 'content-forge')
                }
            />

            <div className="cforge-bg-tertiary/40 cforge-min-h-screen cforge-p-6 cforge-space-y-6">
                <Notice status="error">{error}</Notice>

                {!data && !error && (
                    <p className="cforge-text-sm cforge-text-text-secondary">
                        {__('Loading…', 'content-forge')}
                    </p>
                )}

                {data && (
                    <>
                        <div className="cforge-grid cforge-grid-cols-2 md:cforge-grid-cols-3 xl:cforge-grid-cols-5 cforge-gap-4">
                            {TILES.map((tile) => (
                                <StatTile
                                    key={tile.key}
                                    label={tile.label}
                                    value={counts[tile.key] || 0}
                                    caption={__('generated', 'content-forge')}
                                    href={tile.href}
                                    icon={tile.icon}
                                />
                            ))}
                        </div>

                        {isEmpty ? (
                            <StartHere />
                        ) : (
                            <div className="cforge-grid cforge-grid-cols-1 lg:cforge-grid-cols-2 cforge-gap-6">
                                <AutopilotCard status={autopilot} />
                                <QuickActions />
                            </div>
                        )}

                        {isEmpty && <AutopilotEmpty />}

                        {/* Nothing generated means nothing to clean, so no dead button. */}
                        {!isEmpty && <CleanupCard onDelete={deleteAll} deleting={deleting} />}

                        <PromoPlugins plugins={data.plugins || []} />
                    </>
                )}
            </div>
        </>
    );
}

/**
 * Autopilot health readout.
 *
 * @param {Object} props
 * @param {Object} props.status - Autopilot status from the dashboard endpoint.
 * @return {JSX.Element} The AutopilotCard component.
 */
function AutopilotCard({ status }) {
    let badge = <Badge status="neutral" dot>{__('Disabled', 'content-forge')}</Badge>;

    if (status.enabled && status.stale) {
        badge = <Badge status="error" dot>{__('Dispatcher stalled', 'content-forge')}</Badge>;
    } else if (status.enabled && status.heartbeat === 0) {
        badge = <Badge status="warning" dot>{__('Waiting for first run', 'content-forge')}</Badge>;
    } else if (status.enabled) {
        badge = <Badge status="success" dot>{__('Running', 'content-forge')}</Badge>;
    }

    const lastRun =
        status.minutes_since === null || status.minutes_since === undefined
            ? __('Never', 'content-forge')
            : status.minutes_since === 0
                ? __('Just now', 'content-forge')
                : sprintf(
                    /* translators: %d: number of minutes */
                    __('%d min ago', 'content-forge'),
                    status.minutes_since
                );

    return (
        <Card
            title={__('Autopilot', 'content-forge')}
            subtitle={__('Scheduled AI generation', 'content-forge')}
            icon="⏱️"
            footer={
                <a href={pages.autopilot} className="cforge-no-underline">
                    <Button variant="secondary" size="sm">{__('Manage', 'content-forge')}</Button>
                </a>
            }
        >
            <Row label={__('Status', 'content-forge')} value={badge} />
            <Row label={__('Last run', 'content-forge')} value={lastRun} />
            <Row label={__('Active schedules', 'content-forge')} value={status.active ?? 0} />
            <Row label={__('Paused schedules', 'content-forge')} value={status.paused ?? 0} />

            {status.enabled && status.stale && (
                <Notice status="error" className="!cforge-mb-0">
                    {__('WP-Cron does not appear to be firing. Check that your site is visited regularly, or that a system cron hits wp-cron.php.', 'content-forge')}
                </Notice>
            )}
        </Card>
    );
}

/**
 * Label/value line used inside the Autopilot card.
 *
 * @param {Object} props
 * @param {string} props.label - Left-hand label.
 * @param {*}      props.value - Right-hand value.
 * @return {JSX.Element} The Row component.
 */
function Row({ label, value }) {
    return (
        <div className="cforge-flex cforge-items-center cforge-justify-between cforge-gap-4">
            <span className="cforge-text-sm cforge-text-text-secondary">{label}</span>
            <span className="cforge-text-sm cforge-font-semibold cforge-text-text-primary">{value}</span>
        </div>
    );
}

/**
 * Compact link list to each generator.
 *
 * @return {JSX.Element} The QuickActions component.
 */
function QuickActions() {
    return (
        <Card
            title={__('Quick actions', 'content-forge')}
            subtitle={__('Jump straight into a generator', 'content-forge')}
            icon="⚡"
            footer={
                <a href={pages.settings} className="cforge-no-underline">
                    <Button variant="secondary" size="sm">{__('Settings', 'content-forge')}</Button>
                </a>
            }
        >
            {TILES.map((tile) => (
                <a
                    key={tile.key}
                    href={tile.href}
                    className="cforge-flex cforge-items-center cforge-gap-2 cforge-text-sm cforge-text-text-primary cforge-no-underline hover:cforge-text-primaryHover"
                >
                    <span aria-hidden="true">→</span>
                    {sprintf(
                        /* translators: %s: content type, e.g. "Users" */
                        __('Generate %s', 'content-forge'),
                        tile.label.toLowerCase()
                    )}
                </a>
            ))}
        </Card>
    );
}

/**
 * First-run panel; the primary action on an empty dashboard.
 *
 * @return {JSX.Element} The StartHere component.
 */
function StartHere() {
    return (
        <Card
            title={__('Start here', 'content-forge')}
            subtitle={__('Pick what you need and Content Forge builds it in seconds', 'content-forge')}
            icon="⚡"
        >
            <div className="cforge-grid cforge-grid-cols-1 sm:cforge-grid-cols-2 xl:cforge-grid-cols-3 cforge-gap-3">
                {TILES.map((tile) => (
                    <a
                        key={tile.key}
                        href={tile.href}
                        className="cforge-flex cforge-items-center cforge-gap-3 cforge-p-3 cforge-rounded-lg cforge-border cforge-border-border cforge-no-underline hover:cforge-border-primary focus-visible:cforge-outline focus-visible:cforge-outline-2 focus-visible:cforge-outline-offset-2 focus-visible:cforge-outline-primary"
                    >
                        <span
                            className="cforge-flex cforge-items-center cforge-justify-center cforge-w-8 cforge-h-8 cforge-shrink-0 cforge-rounded-lg cforge-bg-brand-50"
                            aria-hidden="true"
                        >
                            {tile.icon}
                        </span>
                        <span className="cforge-min-w-0">
                            <span className="cforge-block cforge-text-sm cforge-font-semibold cforge-text-text-primary">
                                {tile.label}
                            </span>
                            <span className="cforge-block cforge-text-xs cforge-text-text-secondary">
                                {__('Generate →', 'content-forge')}
                            </span>
                        </span>
                    </a>
                ))}
            </div>
        </Card>
    );
}

/**
 * Autopilot pitch shown before any content exists.
 *
 * @return {JSX.Element} The AutopilotEmpty component.
 */
function AutopilotEmpty() {
    return (
        <Card title={__('Autopilot', 'content-forge')} icon="⏱️">
            <div className="cforge-text-center cforge-py-4">
                <p className="cforge-m-0 cforge-text-sm cforge-font-semibold cforge-text-text-primary">
                    {__('No schedules yet.', 'content-forge')}
                </p>
                <p className="cforge-m-0 cforge-mt-1 cforge-mb-4 cforge-text-sm cforge-text-text-secondary">
                    {__('Autopilot writes and publishes posts on a schedule you set, using your own AI provider.', 'content-forge')}
                </p>
                <a href={pages.autopilot} className="cforge-no-underline">
                    <Button variant="primary" size="sm">{__('Create a schedule', 'content-forge')}</Button>
                </a>
            </div>
        </Card>
    );
}

/**
 * Delete-everything panel.
 *
 * @param {Object}   props
 * @param {Function} props.onDelete - Delete handler.
 * @param {boolean}  props.deleting - Whether a delete is in flight.
 * @return {JSX.Element} The CleanupCard component.
 */
function CleanupCard({ onDelete, deleting }) {
    return (
        <Card
            title={__('Clean up', 'content-forge')}
            subtitle={__('Remove generated content and start fresh', 'content-forge')}
            icon="🧹"
            footer={
                <Button variant="danger" size="sm" disabled={deleting} onClick={onDelete}>
                    {deleting ? __('Deleting…', 'content-forge') : __('Delete all', 'content-forge')}
                </Button>
            }
        >
            <p className="cforge-m-0 cforge-text-sm cforge-text-text-secondary">
                {__('Only content generated by Content Forge is removed — your real posts, users and comments are untouched.', 'content-forge')}
            </p>
        </Card>
    );
}

const container = document.getElementById('cforge-dashboard-app');
if (container) {
    if (window.cforge?.rest_nonce) {
        apiFetch.use(apiFetch.createNonceMiddleware(window.cforge.rest_nonce));
    }
    if (window.cforge?.apiUrl) {
        apiFetch.use(apiFetch.createRootURLMiddleware(window.cforge.apiUrl));
    }

    const { createRoot } = require('react-dom/client');
    const root = createRoot(container);
    root.render(<DashboardApp />);
}
